networks:
  microservices-net:
    driver: bridge

services:

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-gateway
    networks:
      - microservices-net

  api-gateway:
    build:
      context: .
      args:
        APP_NAME: api-gateway
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - kafka
      - redis
    networks:
      - microservices-net

  user-service:
    build:
      context: .
      args:
        APP_NAME: user-service
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://root:root@mongodb:27017/users?authSource=admin
    depends_on:
      mongodb:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - microservices-net

  auth-service:
    build:
      context: .
      args:
        APP_NAME: auth-service
    environment:
      - PORT=3003
      - MONGODB_URI=mongodb://root:root@mongodb:27017/auth?authSource=admin
      - KAFKA_BROKERS=kafka:9092
      - JWT_SECRET=74f4e738d86335c9728796de50e151b3e2ab217a9235452f0ae3b72934803093w
      - JWT_EXPIRES_IN=7d
    depends_on:
      mongodb:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - microservices-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - microservices-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - microservices-net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - microservices-net

  mongodb:
    image: mongo:7-jammy
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_data:/data/db
    networks:
      - microservices-net
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--username",
          "root",
          "--password",
          "root",
          "--authenticationDatabase",
          "admin",
          "--eval",
          "db.adminCommand('ping')",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mongo_data:
